# syntax=docker/dockerfile:1

FROM node:16

ENV NODE_ENV=development

# RUN apt-get update && apt-get install -y python g++ make

WORKDIR /app

# ARG is helpful when we need to just rebuild packages
ARG REBUILD_PACKAGES=false
COPY ["package.json", "yarn.lock", "./"]

# TODO: Seperate dependencies in package.json to reduce image size 
RUN yarn install --production

COPY ["/build", ".env.development", "./"]

COPY ["gcpServiceAccount.dev.json", "./"]

EXPOSE 8081

# ARG is helpful when we need to just rebuild the index due to code changes
ARG REBUILD_INDEX=1
CMD [ "node", "./index.js" ]
