export default [
  {
    name: "BMCC Science and Technology Entry Program (STEP)",
    address: "The City University of New York, 199 Chambers Street,New York, NY 10007",
    borough: "Manhattan",
    description:
      "The BMCC STEP Program is a pre-college enrichment program, that offers free summer and after school STEM academic, robotics, and research classes to limited-income high school students.",
    url: "http://www.bmcc.cuny.edu/research/page.jsp?pid=1262&n=Join%20BMCC%20STEP",
    specialty: "Youth",
    age_lower: 14,
    age_upper: 19,
    email: "bmccstep@gmail.com",
    contact_number: null,
    org_type: "academic",
    requirements:
      "To join STEP you MUST: \n\nBe a NYC HIGH SCHOOL STUDENT, and\nBe a NY STATE RESIDENT (have lived in NY state for 1+ years), and\nSubmit ECONOMIC ELIGIBILITY DOCUMENTATION.  \n\nALL applying students MUST a copy of the appropriate documentation to verify economic eligibility. Appropriate documentation includes the one (1) following:\n\nProof of FREE or REDUCED LUNCH, or\nProof of PUBLIC ASSISTANCE, or\n(family) TAX RETURN showing adjusted gross income. \nPlease see income qualifications:https://www.bmcc.cuny.edu/academics/faculty-affairs/research-and-scholarly-inquiry/student-research-opportunities/economic-eligibility/           Please send pages 1 & 2, which show the household size and adjusted gross income \nAll required documents should be labeled with the student’s name and delivered by:\n\nscanning & emailing to bmccstep@gmail.com, ",
  },
  {
    name: "College Now at Baruch College",
    address: "55 Lexington Ave, New York, NY 10010",
    borough: "Manhattan",
    description:
      "College Now at Baruch College allows qualified NYC public high school juniors and seniors to enroll in courses that earn college credit and provide academic enrichment for FREE.\r\n\r\nThrough College Now students have the opportunity to experience the richness of their campus by having access to their facilities and participating in academic, social, and cultural events. Interaction with Baruch College faculty and students gives College Now students an authentic college experience, eases the transition from high school to college and prepares students for a successful academic career.",
    url: "https://www.baruch.cuny.edu/collegenow/",
    specialty: "High School",
    age_lower: 15,
    age_upper: 19,
    email: "CollegeNow@baruch.cuny.edu",
    contact_number: null,
    org_type: "academic",
    requirements: null,
  },
  {
    name: "College Now at Hunter College",
    address: "695 Park Ave, New York, NY 10065",
    borough: "Manhattan",
    description:
      "Hunter’s College Now program focuses on courses for college or high school credit and other enrichment activities in the humanities, arts, social sciences, sciences and mathematics, all taught by their own full-time or adjunct faculty. Their mission is to introduce high school students of varying skill levels to the rigors and rewards of higher education by connecting them to high-quality scholarship and instruction. All NYC Public High School students participate for free. Classes are geared toward 11th- and 12th-graders\n\nTo cultivate the college experience, thry hold classes on their campus, where students may use their libraries, computer labs, tutorial centers, and dining facilities. Hunter’s College Now frames the college experience with formal orientations and support services specially designed for the high school level.",
    url: "http://www.hunter.cuny.edu/college-now/apply",
    specialty: "High School",
    age_lower: 15,
    age_upper: 19,
    email: "emmendez@hunter.cuny.edu",
    contact_number: null,
    org_type: "academic",
    requirements: null,
  },
  {
    name: "Coursera",
    address: "Online",
    borough: "Online",
    description:
      "Coursera is another e-learning platform that allows you to be taught by professors from Ivy League schools and other elite schools like the University of Pennsylvania, Stanford and Duke. Over 1400 courses are available for free, and topics available include C++, marketing, engineering and psychology. Through these courses, you can build up general knowledge in specific areas as well as gain Certifications to add to your resume",
    url: "https://www.coursera.org/",
    specialty: "Online ",
    age_lower: null,
    age_upper: null,
    email: null,
    contact_number: null,
    org_type: "academic",
    requirements: null,
  },
  {
    name: "Homes for the Homeless",
    address: "36 Cooper Square, 3rd Floor, New York, NY 10003",
    borough: "Manhattan",
    description:
      'Homes for the Homeless provides a well staffed and well resourced academic and extracirricular program for homeless children and adolescents. Provides early childhood education programs and daycare, as well as an after school enrichment program to "supplement classroom education and emphasize social development through group activities, conflict resolution workshops, community service and mentoring". ',
    url: "https://www.hfhnyc.org/",
    specialty: "Youth",
    age_lower: 3,
    age_upper: 17,
    email: "contact@hfhnyc.org",
    contact_number: "(212) 529-5252",
    org_type: "academic",
    requirements: null,
  },
  {
    name: "Patnership for the Homeless",
    address: "305 7th Ave, New York, NY 10001",
    borough: "Manhattan",
    description:
      "Homeless or Homeless-At-Risk Resource Center- \nEducation: Disrupt Generational Cycles\r\nDisrupt the generational cycle of homelessness by ensuring children in shelters, or at risk of homelessness, have continuous access to school and adults have access to financial training\r\n\r\n-Provide financial education trainings through our corporate partners\r\n-Offer tenants’ rights/responsibilities workshops\r\n-Advocate to keep children in school and placed in shelters near their schools\r\n-Connect children to volunteer tutors to keep them on track at school",
    url: "https://partnershipforthehomeless.org/",
    specialty: "General (all adults)",
    age_lower: null,
    age_upper: null,
    email: "info@pfth.org",
    contact_number: "(212) 645-3444",
    org_type: "academic",
    requirements: null,
  },
  {
    name: "The Door",
    address: "555 Broome St, New York, NY 10013",
    borough: "Manhattan",
    description:
      "The Door serves nearly 11,000 young people from all over New York City, with a wide range of services including reproductive health care and education, mental health counseling and crisis assistance, legal assistance, GED and ESOL classes, tutoring and homework help, college preparation services, career development, job training and placement, supportive housing, sports and recreational activities, arts, and nutritious meals – all for free, completely confidentially, and under one roof.",
    url: "https://door.org/",
    specialty: "Youth",
    age_lower: 12,
    age_upper: 24,
    email: "Waiting for Reponse",
    contact_number: null,
    org_type: "academic",
    requirements: null,
  },
  {
    name: "Youth Action YouthBuild (YAYB)",
    address: "206 E 118th St New York, NY 10035",
    borough: "Manhattan",
    description:
      "YAYB, headquartered in East Harlem, is dedicated to putting young adults in New York City aged 17-24 on the path to self-empowerment. We provide job skills training, job placement services, high school equivalency and a safe environment where our students are positively encouraged to become leaders in their communities.",
    url: "https://www.youthaction.nyc/",
    specialty: "Youth",
    age_lower: 17,
    age_upper: 24,
    email: "info@yayb.org",
    contact_number: null,
    org_type: "academic",
    requirements: null,
  },
];
