export default [
  {
    name: "Ali Forney Drop In Center",
    address: "321 W 125th St, New York, NY 10027",
    borough: "Manhattan",
    description:
      "Provides Initial Intake Support; Medical Checkup, Psychiatric Evaluation, HIV Counseling and Testing, Medicaid Enrollment , Warm Meals, Hot Showers, and 24 Hour access to services. It terms of ongoing support, it includes Group Therapy, Mental Health Counseling, Support Groups, Workshops, Continued Medical Care, Case Management, Recreational Activities that provide structure and focus, Prevention & Treatment adherence Counseling, and Mental Health groups & Support Counseling",
    url: "https://www.aliforneycenter.org/",
    specialty: "LGBTQIA+",
    age_lower: 16,
    age_upper: 24,
    email: null,
    contact_number: "(212) 206-0574",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "Antonio Olivieri Drop-In Center",
    address: "257 West 30th Street,New York, NY 10001",
    borough: "Manhattan",
    description:
      "Drop-In center offers on-site, 24-hour services including meals, clothing, and showers.. Clients may drop in during business hours, see intake, and may join the program if they qualify (cannot be part of another program for at least the past year).",
    url: "https://www.urbanpathways.org/programsandservices",
    specialty: "General (all adults)",
    age_lower: 18,
    age_upper: null,
    email: "outreachteam@urbanpathways.org",
    contact_number: "212-947-3211",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "Bowery Mission: Bowery Campus",
    address: "227 Bowery, New York, NY, 10002",
    borough: "Manhattan",
    description:
      "Women's & Men's Day Center- Provides each guest with nourishment physically, emotionally and spiritually. Provides Daily Meals- No ID required and no long process neccessary to get a plate to eat! Most meals are preceded by a short Chapel Service. You do not have to attend to get food, but are invited to come and be fed, both spiritually an physically! Breakfast(to-go): 8:00 am, Lunch (to-go): 1pm. Clothing & Showers: Works with partners to provide showers on a limited basis. Sign up takes place at 7:30 am (Men: Tuesdays & Wednesdays) (Women: Fridays). Medical Services: Barrier-free medical services by licensed professionals who volunteer to provide the best care possible. If they can't serve you, volunteers will provide a doctor's referral to someone who can. Volunteers also help people apply for Medicare or Medicaid. Offers care Mon-Fri, 8am-4pm, through mobile medical van outside Bowery Campus. Pantry Items: Welcomes guests to visit pantry, where one can receive canned goods and pantry staples; items vary by availability. Mon-Fri, 9:30am-11:30am",
    url: "https://www.bowery.org/get-help/",
    specialty: null,
    age_lower: null,
    age_upper: null,
    email: null,
    contact_number: "212-674-3456",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "Covenant House NY",
    address: "550 10th Ave, New York, NY 10018",
    borough: "Manhattan",
    description:
      "Covenant House New York (CHNY) has been a leader in providing residential services to vulnerable homeless, runaway, and exploited youth.  As the largest provider of runaway and homeless youth services in New York City, CHNY serves over 1,900 young adult ages 16-24 annually with an operating budget of over 25 million dollars.  We facilitate our services using trauma-informed principles to help homeless youth leave the streets and achieve independence. We also advocate for systemic change through public policy while promoting awareness of critical issues related to youth homelessness.",
    url: "https://www.covenanthouse.org",
    specialty: "Youth Organization",
    age_lower: 14,
    age_upper: 20,
    contact_number: null,
    email: "info@covenanthouse.org",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "Euphrasian Residence",
    address: "337 East 17th Street, NY, NY 10003, USA",
    borough: "Manhattan",
    description:
      "Euphrasian Residence serves teenage girls in crisis. The young women receive a comprehensive psychological, psychiatric, medical and educational evaluation by professional staff to fully assess their needs and determine the best possible long-term solution for ongoing care. During their short term stay, residents attend school on-site, and participate in a variety of therapeutic, social and recreational activities.",
    url: "https://goodshepherds.org/program/euphrasian-residence/",
    specialty: "Youth (Girls)",
    age_lower: null,
    age_upper: null,
    email: null,
    contact_number: "(212) 475-4245",
    org_type: "mentalWellness",
    requirements: "Must have been referred by the New York City Administration for Children’s Services.",
  },
  {
    name: "HEAT",
    address: "450 Clarkson Avenue, Brooklyn, NY 11203",
    borough: "Brooklyn",
    description:
      "Provides medical services to LGBT youth, including HIV testing, mental health services and case management for HIV+ youth. ",
    url: "https://heatprogram.org/about-us-take-2",
    specialty: "LGBTQ+ Youth Primarily",
    age_lower: null,
    age_upper: null,
    email: "heatprogram450@gmail.com",
    contact_number: "(718) 613-8543",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "Homes for the Homeless",
    address: "36 Cooper Square, 3rd Floor, New York, NY 10003",
    borough: "Manhattan",
    description:
      "Partners with mobile health clinics to provide health services to individuals and families. Specifically, partners with the Saratoga family shelter to provide substance abuse and addiction treatment.",
    url: "https://www.hfhnyc.org/serving-nyc/parents/health-and-wellness/",
    specialty: "General (adulta and youth)",
    age_lower: null,
    age_upper: null,
    email: "contact@hfhnyc.org",
    contact_number: "(212) 529-5252",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "ICL ",
    address: "125 Broad St, New York, NY 10004",
    borough: "Manhattan",
    description:
      "ICL helps people of all backgrounds address emotional, mental health and developmental disability challenges. All programs are grounded in person-centered care because all aspects of a person’s life effect their health and well-being. Programs include: housing, Treatment Services, Coordinated Care, Services for Children and Families, Intellectual Development Disabilities",
    url: null,
    specialty: null,
    age_lower: null,
    age_upper: null,
    email: "info@iclinc.org",
    contact_number: null,
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "myTherapyNYC",
    address: "928 Broadway, Suite 405/806, NYC 10010",
    borough: "Manhattan",
    description:
      "myTherapyNYC provides group or individual therapy, specialized therapy for members of the LGBT community, Meditation therapy, self-esteem building, and a variety of other services.",
    url: "https://mytherapynyc.com/individual-counseling-nyc/",
    specialty: "LGBT Therapy, Individual or Group Therapy, Meditation Therapy",
    age_lower: null,
    age_upper: null,
    email: " info@mytherapynyc.com",
    contact_number: " 646-449-0491",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "New Alternatives",
    address: "410 W 40th St, New York, NY 10018",
    borough: "Manhattan",
    description:
      "New Alternatives is a program that provides care for LGBT homeless youth in the form of takeout meals at the Metro Baptist Church, as well as support groups and STI testing. ",
    url: "https://www.newalternativesnyc.org/client-services",
    specialty: "LGBTQ+ Youth to Young Adulthood",
    age_lower: null,
    age_upper: null,
    email: "info@newalternativesnyc.org",
    contact_number: "(718) 300-0133",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "NYC Well",
    address: "Online",
    borough: "Online",
    description:
      "NYC Well is your connection to free private mental health support. You can connect to a counselor or peer specialist by phone, text, or chat and get help with problems like stress, depression, anxiety, or drug and alcohol misuse.\n\nText a counselor now\r\n\r\nText WELL to 65173 at anytime to communicate with a counselor. When prompted text:\r\n\r\n1 for English\r\n2 for Spanish\r\n3 for Chinese\n\nCall NYC Well\r\n\r\nCall 888-NYC-WELL (888-692-9355) to speak with a counselor at any time. When prompted, press:\r\n3 for Spanish\r\n4 for Chinese\n\n",
    url: "https://nycwell.cityofnewyork.us/en/",
    specialty: "All",
    age_lower: null,
    age_upper: null,
    email: null,
    contact_number: "888-692-9355",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "Partnership for the Homeless",
    address: "305 7th Ave, New York, NY 10001",
    borough: "Manhattan",
    description:
      "Homeless or Homeless-At-Risk Resource Center- \nPrevent people from cycling in and out of the crisis that can lead to homelessness via the provision of basic health and well-being services and appropriate referrals:\n-Connect low-income New Yorkers to therapeutic services\n-Provide classical clinical support alongside emotional well-being training\n-Apply a trauma-informed lens across services to identify trauma symptoms in clients\n-Referrals for primary care and long-term mental-health services\n-Provide emergency food via partnership with FEMA and local soup kitchens/food pantries\n",
    url: "https://partnershipforthehomeless.org/",
    specialty: "General (all adults)",
    age_lower: null,
    age_upper: null,
    email: "info@pfth.org",
    contact_number: "(212) 645-3444",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "Peter Jay Sharp House",
    address: null,
    age_lower: null,
    age_upper: null,
    borough: null,
    contact_number: null,
    description: null,
    email: null,
    org_type: "mentalWellness",
    specialty: null,
    url: null,
    requirements: null,
  },
  {
    name: "Residential Services",
    address: null,
    age_lower: null,
    age_upper: null,
    borough: null,
    contact_number: null,
    description: null,
    email: null,
    org_type: "mentalWellness",
    specialty: null,
    url: null,
    requirements: null,
  },
  {
    name: "Safe Horizon: Streetwork Project",
    address: "209 West 125th St - 2nd Floor,New York, NY 10027",
    borough: "Manhattan",
    description:
      "Streetwork Project operates Drop-In Centers where youth experiencing homelessness can socialize in a safe non-judgmental place. In the Drop-Ins, young people can get help with: Daily necessities such as meals, showers, clothing, wellness activities, Medical care, Legal assistance, Mental health services, Sexual health help including HIV prevention materials and testing, Obtaining identification, obtaining public benefits, linkages to emergency shelter, housing advocacy",
    url: "https://www.safehorizon.org/streetwork/",
    specialty: "Youth",
    age_lower: 13,
    age_upper: 25,
    email: "Website@safehorizon.com (will update if neccessary)",
    contact_number: null,
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "The Breathing Project: Yoga for Mental Wellness",
    address: "15 West 26th St., 10th Floor, NYC",
    borough: "Manhattan",
    description:
      "Yoga for Mental Wellness (YMW) is a community service project of The Breathing Project, that provides free therapeutic yoga classes in New York City for adults of any age or fitness level living with emotional distress or mental illness. Experience and research suggest that yoga can be a powerful tool for addressing emotional and mental illness. For many of us, the regular practice of yoga can lift the mood, reduce stress, enhance problem-solving, improve strength and flexibility, lessen fatigue and increase energy.\n\nA typical YMW class at The Breathing Project involves the slow, careful movement of yoga postures, focused breathing coordinated with movement, attention to the present moment, embodied exploration of the body and its resources, compassionate self-care and deep relaxation.  YMW classes at The Breathing Project are limited to 8 students to allow for individualized teaching, the growth of connections between student, teacher and classmates, and the development of healing communities.\n\nTuesdays: 10:30am-11:45am\nThursdays: 10:30am-11:45am\nMust Register in Advance Through Email or Phone",
    url: "https://yogaformentalwellness.org/open-classes/",
    specialty: "All",
    age_lower: null,
    age_upper: null,
    email: "elizabeth@yogaformentalwellness.org",
    contact_number: "551-358-2269",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "The Door",
    address: "424 East 147th Street The Bronx, NY 10455",
    borough: "The Bronx",
    description:
      "The Door's Bronx Youth Center provides High School Equivalency (HSE), Post-Secondary, Jobs, Internships, and Work Training, and Additional Support/Fun Activities to young people in The Bronx who have faced homelessness, the criminal justice system's effects, and the foster care system. This location also provides FREE programs including Intake Sessions on Tuesdays at 2PM. ",
    url: "https://door.org/programs-services/bronx-youth-center/",
    specialty: "Youth",
    age_lower: null,
    age_upper: null,
    email: "simperati@door.org",
    contact_number: "212-941-9090 Ext: 3522",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "The Door",
    address: "555 Broome St, New York, NY 10013",
    borough: "Manhattan",
    description:
      "The Door serves nearly 11,000 young people from all over New York City, with a wide range of services including reproductive health care and education, mental health counseling and crisis assistance, legal assistance, GED and ESOL classes, tutoring and homework help, college preparation services, career development, job training and placement, supportive housing, sports and recreational activities, arts, and nutritious meals – all for free, completely confidentially, and under one roof.",
    url: "https://door.org/",
    specialty: "Youth",
    age_lower: 12,
    age_upper: 24,
    email: null,
    contact_number: null,
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "The Lantern Community ",
    address: "495 8th Avenue, 20th Floor, New York, NY 10001",
    borough: "Manhattan",
    description:
      "The Lantern Community provides mental health and wellnes programs for their housed youths, working with psychiatrists and social workers to help previously homeless youth work through any trauma or difficulties they are experiencing as a result of mistreatment from the foster system. ",
    url: "https://lanterncommunity.org/programs/health-and-wellness/",
    specialty: "Youth",
    age_lower: 18,
    age_upper: 26,
    email: "Waiting for email",
    contact_number: "212.398.3074",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "The LGBT Center ",
    address: "208 W 13th St, New York, NY 10011",
    borough: "Manhattan",
    description:
      "Mental health assistance to LGBT youth, as well as treatment for substance abuse and treatment programs for safe drug usage. ",
    url: "https://gaycenter.org/family-youth/youth/",
    specialty: "LGBTQ+ Youth",
    "Age Range": "13-20",
    age_lower: 13,
    age_upper: 20,
    email: null,
    contact_number: "212.620.7310",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "The Reciprocity Foundation",
    address: " 151 W 19th St, New York, NY 10011",
    borough: "Manhattan",
    description:
      "Reciprocity has been pioneering holistic health programs for the Social Services sector in New York City.  Reciprocity was the first comprehensive holistic program for healing young adults facing homelessness, incarceration & trauma. The new space offers  meditation, acupuncture, massage, trauma therapy, sound healing & community meals to all New Yorkers in need of trauma support & recovery.",
    url: "https://www.reciprocityfoundation.org/",
    specialty: "Youth and LGBTQIA+",
    age_lower: null,
    age_upper: null,
    email: "book@ReciprocityFoundation.org",
    contact_number: null,
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "Vita: Women's Mental Wellness Program",
    address: "110-45 Queens Boulevard, Suite #104, Forest Hills, NY, 11375",
    borough: "Queens",
    description:
      "Vita Women Mental Wellness Programs Includes:\n\r\nDirecting to resources (Mental Health Professionals)\r\nBe part of the recovery models for each women in need\r\nProvide a safe haven for support groups\r\nHost workshops to provide information, tools, and resources.\r\nHopefully in the future start a granted funded program with advocate and counselors actively helping out the community.",
    url: "http://www.vitacenterny.org/vita-womens-mental-wellness-initiative",
    specialty: "Women",
    age_lower: 18,
    age_upper: null,
    email: "info@vitacenterny.org",
    contact_number: "(718) 880-7321",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "Youth & Young Adult Specialized Care Center Bellevue Hospital",
    address: "462 First Avenue, New York, New York 10016",
    borough: "Manhattan",
    description:
      "Provider of comprehensive LGBTQ+ friendly sexual health and HIV related clinical, psychological and support services for NYC’s youth and young adults regardless of their ability to pay. ",
    url: "https://med.nyu.edu/pediatrics/pedsid/clinical-services/youth-young-adult-specialized-care-center",
    specialty: "LGBTQ+ Youth",
    age_lower: 13,
    age_upper: 24,
    email: null,
    contact_number: "(212) 263-1534",
    org_type: "mentalWellness",
    requirements: null,
  },
  {
    name: "Care for the Homeless",
    address: "30 E 33rd St. 5th Floor, New York, New York, 10016",
    borough: "Manhattan",
    description:
      "Provides high quality, patient-centered health care to all those experiencing homelessness regardless of their ability to pay. Service include: primary care services, behavioral health services, population health management, podiatry. ",
    url: "https://www.careforthehomeless.org/",
    specialty: "General",
    age_lower: null,
    age_upper: null,
    email: null,
    contact_number: "(212) 366-4459",
    org_type: "mentalWellness",
    requirements: null,
  },
];
