export default [
  {
    name: "All Star Code Summer Institute",
    address: "85 Broad St FL 28 New York, NY 10004-2783",
    borough: "Manhattan",
    description:
      "All Star Code prepares young Black and Latino men for tech careers by providing mentorship, industry exposure, and training in Computer Science. Their flagship program, the Summer Intensive (SI), is a FREE six week program designed to give high school boys the access and exposure they need to become successful tech entrepreneurs. Through real-world experiences at top tech companies, and hands-on, project-based learning, All Stars finish the program with both coding skills and an entrepreneurial mindset.",
    url: "https://allstarcodeorg.github.io/apply/#",
    specialty: "High School",
    age_lower: 14,
    age_upper: 19,
    email: "admissions@allstarcode.org",
    contact_number: null,
    requirements:
      "High School (not required to be enrolled in school) age; Male; Preference given to Black & Latino applicants; No coding experience necessary; Only 40 students accepted per year.",
    org_type: "professionalServices",
    lat: 40.7039915,
    long: -74.0110917,
  },
  {
    name: "Beginning with Children: College Prep Afterschool Program",
    address: "217 Havemeyer St. 2nd Floor, Brooklyn, NY 11211",
    borough: "Brooklyn",
    description:
      "BwC College Prep Afterschool Program is a college and career preparatory program for high school students. We offer free academic tutoring, SAT and Regents prep, college and financial aid workshops, mentoring, college tours and paid summer internships. Click Link to Apply.",
    url: "https://docs.google.com/forms/d/e/1FAIpQLSfYnhbifK0B3kfnIQmBTmWK3i9zutir70p8pLH-XpCd4KGgZA/viewform",
    specialty: "Youth",
    age_lower: 14,
    age_upper: 19,
    email: "legacynetwork@bwcf.org",
    contact_number: null,
    requirements: "High School students who live or attend school in Brooklyn.",
    org_type: "professionalServices",
    lat: 40.7092986,
    long: -73.9587367,
  },
  {
    name: "BRC",
    address: "131 West 25th Street, 12th Floor, NY, NY 10001",
    borough: "Manhattan",
    description: null,
    url: null,
    specialty: "Regular",
    age_lower: 18,
    age_upper: null,
    email: "info@brc.org",
    contact_number: null,
    requirements: null,
    org_type: "professionalServices",
    lat: 40.7449235,
    long: -73.9931127,
  },
  {
    name: "Bronx Junior Photo League at the Bronx Documentary Center",
    address: "BRONX DOCUMENTARY CENTER, 614 COURTLANDT AVENUE, BRONX, NY 10451",
    borough: "Bronx",
    description:
      "The Bronx Junior Photo League (BJPL) is a free photography and journalism program serving middle through high school students.\n\nTheir free afterschool and summer photojournalism programs teach middle and high school Bronx students to use photography, writing, and research to explore social justice issues, preparing them for college and future careers. The program includes visits with internationally-renowned photographers, field trips to major cultural institutions and media outlets, and opportunities for life-changing international travel. Students and families participate in extensive college prep programming, including one-on-one counseling, financial aid workshops, and college tours. Applications for 2022 open on 5/22.",
    url: "https://www.bronxdoc.org/education/bronx-junior-photo-league",
    specialty: "Youth",
    age_lower: 13,
    age_upper: 18,
    email: "INFO@BRONXDOC.ORG",
    contact_number: "718.993.3512",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.8179993,
    long: -73.918599,
  },
  {
    name: "Brooklyn Museum Work-Study and Art Classes",
    address: "200 Eastern Parkway, Brooklyn, New York 11238-6052",
    borough: "Brooklyn",
    description:
      "Build your résumé while taking an art class free of charge in this internship for teens! As a work-study student volunteer, you’ll assist professional teaching artists in classes for students ages six and up, then take your own art class with other teens for free.\n\nYou will:\n\nAssist and be mentored by a professional teaching artist\nPrepare art supplies\nWork one-on-one with students\nBuild your communication, group management, and teaching skills\nTake your own free teen art class (valued at $285)\nEarn up to 36 hours of volunteer credit\nBe able to request a letter of recommendation upon completing the program\nTo apply, you need to be 1) a high school sophomore, junior, or senior, and 2) able to commit to the activities below:\n\nAttend all ten sessions of the course you assist (30 hours total)\nAttend all sessions of the free studio class of your choice\nAttend the orientation meeting (March 5), mid-semester career development (March 13, March 19, and May 1), and end-of-semester reflection (May 21)",
    url: "https://www.brooklynmuseum.org/education/teens/gallery-studio-work-study",
    specialty: "High School",
    age_lower: 13,
    age_upper: 18,
    email: "gallery-studio@brooklynmuseum.org",
    contact_number: "718.638.5000",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.6712083,
    long: -73.9636299,
  },
  {
    name: "CAMBA Learning to Work Program",
    address: "1720 Church Ave, Brooklyn, NY, 11226",
    borough: "Brooklyn",
    description:
      "CAMBA’s Learning to Work (LTW) program helps to re-engage students who have dropped out or fallen behind in credits to graduate high school. LTW programs are offered at ten transfer high schools and one Young Adult Borough Center (YABC). Transfer high schools are small, full-time high schools designed to motivate students who have fallen behind in credits. YABCs offer evening academic programs for high school students who cannot attend during the day. We provide a wide range of diverse programming including academic and student support, career and educational development, college advising and preparation, work preparation, skills development, and paid internships with companies like Edible Arrangements, BRIC, Vibe Magazine and many more.",
    url: "https://camba.org/programs/learning-to-work/",
    specialty: "Young Adult",
    age_lower: 16,
    age_upper: null,
    email: "info@camba.org",
    contact_number: "718.226.0436",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.6490908,
    long: -73.9633697,
  },
  {
    name: "Codecademy",
    address: "Online",
    borough: "Online",
    description:
      "Codecademy is an online interactive platform that offers free coding classes in 12 different programming languages including Python, Java, Go, JavaScript , Ruby, SQL, C++, Swift, and Sass, as well as markup languages HTML and CSS.",
    url: "https://www.codecademy.com/register",
    specialty: "Online",
    age_lower: null,
    age_upper: null,
    email: null,
    contact_number: null,
    requirements: null,
    org_type: "professionalServices",
  },
  {
    name: "CoLab by CultureHub",
    address: "47 Great Jones St, New York, NY 10012",
    borough: "Manhattan",
    description:
      "Runs through the month of July. CoLab offers free summer workshops for young artists ages 14–19 who want to explore new ways of combining art and technology. In each workshop, participants meet and work with a teaching artist who introduces new tools and creative approaches. In a fun and interactive setting, young artists will put their own spin on technology to create an original work of art",
    url: "https://www.culturehub.org/colab",
    specialty: "High School",
    age_lower: 14,
    age_upper: 19,
    email: "colab@culturehub.org",
    contact_number: "917 463 3917",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.7265254,
    long: -73.9926215,
  },
  {
    name: "Institute for Career Development",
    address: "123 William Street 5th Floor, New York, NY 10038    ",
    borough: "Manhattan",
    description:
      "ICD is a not-for-profit workforce development organization based in New York City. Our mission is to help people transform their lives through career development and employment. Before coming to ICD, our students are unemployed an average of two years and most are living at or below the poverty line.\nICD’s graduates receive competitive starting salaries, earning on average two dollars over the NYS minimum wage.\nMany graduates go on to earn substantially higher salaries and receive health benefits.",
    url: "https://www.icdnyc.org/contact",
    specialty: "Young people with disabilities, veterans, youth in transition, and youth with asperger syndrome",
    age_lower: 16,
    age_upper: 24,
    email: null,
    contact_number: "(212) 585-6000",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.7094756,
    long: -74.0072955,
  },
  {
    name: "Made in NY Building Animation Skills @ NeON Centers",
    address: "198 East 161st Street \nBronx, NY 10451",
    borough: "Bronx",
    description:
      "The Made in NY Animation Project offers NYC youth the opportunity to engage in storytelling, gain technical skills in 3D computer animation, and qualify for paid internships in the field.",
    url: "https://www1.nyc.gov/site/mome/industries/animation-project.page",
    specialty: "Young Artists",
    age_lower: 12,
    age_upper: 24,
    email: "group@theanimationproject.org.",
    contact_number: "(917) 282-0933",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.8259599,
    long: -73.9208508,
  },
  {
    name: "Made in NY Building Animation Skills @ NeON Centers",
    address: "444 Thomas S. Boyland Street\nBrooklyn, NY 11212",
    borough: "Brooklyn",
    description:
      "The Made in NY Animation Project offers NYC youth the opportunity to engage in storytelling, gain technical skills in 3D computer animation, and qualify for paid internships in the field.",
    url: "https://www1.nyc.gov/site/mome/industries/animation-project.page",
    specialty: "Young Artists",
    age_lower: 12,
    age_upper: 24,
    email: "group@theanimationproject.org.",
    contact_number: "(917) 282-0931",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.6698684,
    long: -73.9141067,
  },
  {
    name: "Made in NY Building Animation Skills @ NeON Centers",
    address: "127 West 127th Street \nNew York, NY 10027",
    borough: "Manhattan",
    description:
      "The Made in NY Animation Project offers NYC youth the opportunity to engage in storytelling, gain technical skills in 3D computer animation, and qualify for paid internships in the field.",
    url: "https://www1.nyc.gov/site/mome/industries/animation-project.page",
    specialty: "Young Artists",
    age_lower: 12,
    age_upper: 24,
    email: "group@theanimationproject.org.",
    contact_number: "(917) 282-0932",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.809875,
    long: -73.9458556,
  },
  {
    name: "Made in NY Building Animation Skills @ NeON Centers",
    address: "162-24 Jamaica Avenue \nJamaica, NY 11432",
    borough: "Queens",
    description:
      "The Made in NY Animation Project offers NYC youth the opportunity to engage in storytelling, gain technical skills in 3D computer animation, and qualify for paid internships in the field.",
    url: "https://www1.nyc.gov/site/mome/industries/animation-project.page",
    specialty: "Young Artists",
    age_lower: 12,
    age_upper: 24,
    email: "group@theanimationproject.org.",
    contact_number: "(917) 282-0935",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.7044211,
    long: -73.7970689,
  },
  {
    name: "Made in NY Building Animation Skills @ NeON Centers",
    address: "340 Bay Street \nStaten Island, NY 10301",
    borough: "Staten Island",
    description:
      "The Made in NY Animation Project offers NYC youth the opportunity to engage in storytelling, gain technical skills in 3D computer animation, and qualify for paid internships in the field.",
    url: "https://www1.nyc.gov/site/mome/industries/animation-project.page",
    specialty: "Young Artists",
    age_lower: 12,
    age_upper: 24,
    email: "group@theanimationproject.org.",
    contact_number: "(917) 282-0934",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.6339765,
    long: -74.0754038,
  },
  {
    name: "Made in NY Post Production Training Program",
    address: "63 Flushing Ave, Brooklyn, NY 11205",
    borough: "Brooklyn",
    description:
      "This free, five-week program trains participants to use industry-standard software, preparing them for work in New York's many post facilities. After graduation from the program, students will receive job placement assistance and two years of career guidance and support. Participants learn the basics of the following programs:\nAvid Media Composer\nAdobe Premiere Pro \nAdobe Photoshop\nAdobe After Effects \nNuke",
    url: "https://bwiny.org/post/apply/",
    specialty: "Young Artists",
    age_lower: 21,
    age_upper: null,
    email: "post@bwiny.org",
    contact_number: "347-470-3231.",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.6984715,
    long: -73.9777647,
  },
  {
    name: "Made in NY Production Assistant Training Program",
    address: "63 Flushing Ave, Brooklyn, NY 11205",
    borough: "Brooklyn",
    description:
      "The “Made in NY” Production Assistant Training Program helps young people access their potential in the film and television industry. PAs CAN EXPECT:\nLong (12 to 16 hour) days, often starting early in the morning\nPhysical labor, on your feet\nOutdoor work in all weather\nFreelance work – working day-to-day and project-to-project\nMost jobs will not include benefits and the work schedule is not typically known in advance\nPay rates of about $150-$210/day",
    url: "https://bwiny.org/made-in-ny-pa-training-program/apply/",
    specialty: "Young People",
    age_lower: 18,
    age_upper: 24,
    email: "pa@bwiny.org",
    contact_number: "718-237-2017 x 145",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.6984715,
    long: -73.9777647,
  },
  {
    name: "Made in NY Writer's Room",
    address: "250 Hudson Street, Suite 700, New York, New York 10013",
    borough: "Manhattan",
    description:
      "The Made in NY Writers Room (the “Fellowship”) provides emerging television writers, who represent diverse backgrounds and lack access to the industry, with six months of intensive early-career training. Up to 12 writers or writing teams will be selected for the paid fellowship that includes monthly one-on-one mentorship sessions with television showrunners, ongoing roundtables with other writers and industry executives, ongoing career development resources and trainings, and the opportunity to build a refined portfolio of at least two sample scripts.",
    url: "https://www.wgaeast.org/MINY-writers-room/",
    specialty: "Young Writers",
    age_lower: null,
    age_upper: null,
    email: null,
    contact_number: "212-767-7800",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.7249946,
    long: -74.0072895,
  },
  {
    name: "Partnership for the Homeless",
    address: "305 7th Ave, New York, NY 10001",
    borough: "Manhattan",
    description:
      "Homeless or Homeless-At-Risk Resource Center- \nEducation: Disrupt Generational Cycles\r\nDisrupt the generational cycle of homelessness by ensuring children in shelters, or at risk of homelessness, have continuous access to school and adults have access to financial training\r\n\r\n-Provide financial education trainings through our corporate partners\r\n-Offer tenants’ rights/responsibilities workshops\r\n-Advocate to keep children in school and placed in shelters near their schools\r\n-Connect children to volunteer tutors to keep them on track at school",
    url: "https://partnershipforthehomeless.org/",
    specialty: "General (all adults)",
    age_lower: null,
    age_upper: null,
    email: "info@pfth.org",
    contact_number: "(212) 645-3444",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.7466546,
    long: -73.9933453,
  },
  {
    name: "Sound Thinking NYC",
    address: "101 W. 31st Street, 6th Floor, New York, NY 10001",
    borough: "Manhattan",
    description:
      "Sound Thinking NYC is a free program especially designed to open doors for young women to explore careers in the music industry.",
    url: "https://creativeartsteam.org/programs/sound-thinking-nyc",
    specialty: "Young Women",
    age_lower: null,
    age_upper: null,
    email: "applications@soundthinkingnyc.org",
    contact_number: "(212) 652-2832",
    requirements: "10th-12th grade",
    org_type: "professionalServices",
    lat: 40.7481691,
    long: -73.9894683,
  },
  {
    name: "The Association of Community Employment Programs for the Homeless (ACE)",
    address: "30-30 Northern Blvd., Ste. B100, Long Island City, NY 11101",
    borough: "Queens",
    description:
      "Project Comeback- \nA 4-6 month vocational rehabilitation program that provides recovering homeless individuals with the skills, support services, and motivation needed to obtain and sustain full-time employment and economic independence.\n\nParticipants receive job-readiness training, supported work experience (providing maintenance services to New York City streets and parks), Adult Basic Education, hard-skills training (Occupational Safety & Health Administration [OSHA]; Food Protection) and vocational support services, including life skills development and job search assistance. Program activities take place seven days each week year-round, with each participant attending five days weekly, graduating from the program once he/she finds full-time employment.\n\nProject Stay-\nA life-long employment retention program that supports graduates as they acclimate to the world of work and transition to self-sufficiency.\nProject Stay offers groups, case management, social events and educational opportunities\ngeared toward professional advancement. Graduates who maintain employment are eligible for financial incentive\n\n\nProject Home-\nProject Home, ACE’s housing program, offers a 3-year subsidy to select graduates. Project Home provides a stable environment from which graduates can pursue vocational growth, increased earning power and enhanced independent living skills\n\nAll services are provided free of charge to program participants.\n\nThe admission criteria for Project Comeback are as follows:\n\n• Housing: all applicants must have a history of homelessness.\n• Sobriety: all applicants must have at least 30 days of documented sobriety.\n• Criminal History: applicants may not have a violent or aggressive criminal history.\n• Medical and Behavioral Health History: applicants must be able to lift, stand and walk for an 8-hour shift; applicants on medication for an Axis-1 diagnosis must have six months of documented stability; applicants cannot have had an inpatient psychiatric hospitalization in the previous six months.\n•",
    url: "https://www.acenewyork.org/",
    specialty: "General (all adults)",
    age_lower: 18,
    age_upper: null,
    email: "emcnierney@acenewyork.org",
    contact_number: null,
    requirements: "Applicants must be at least 18 years of age and a U.S. citizen or legal resident.",
    org_type: "professionalServices",
    lat: 40.7512283,
    long: -73.9335479,
  },
  {
    name: "The Door",
    address: "555 Broome St, New York, NY 10013",
    borough: "Manhattan",
    description:
      "The Door serves nearly 11,000 young people from all over New York City, with a wide range of services including reproductive health care and education, mental health counseling and crisis assistance, legal assistance, GED and ESOL classes, tutoring and homework help, college preparation services, career development, job training and placement, supportive housing, sports and recreational activities, arts, and nutritious meals – all for free, completely confidentially, and under one roof.",
    url: "https://door.org/",
    specialty: "Youth",
    age_lower: 12,
    age_upper: 24,
    email: null,
    contact_number: null,
    requirements: null,
    org_type: "professionalServices",
    lat: 40.7241123,
    long: -74.0055596,
  },
  {
    name: "The Lantern Community",
    address: "495 8th Avenue, 20th Floor, New York, NY 10001",
    borough: "Manhattan",
    description:
      'The Lantern Community provides several programs for youth housed in their shelters, including programs for employment and education, nutrition and culinary arts, arts, culture, fitness programs and a "Moving On" program that prepares housed youths with a plan to move out and live independently and successfully. ',
    url: "https://lanterncommunity.org/programs/",
    specialty: "Youth",
    age_lower: 18,
    age_upper: 26,
    email: "Waiting for email",
    contact_number: "212.398.3071",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.7528845,
    long: -73.9932115,
  },
  {
    name: "Vita Teaching for Children",
    address: "110-45 Queens Boulevard, Suite #104, Forest Hills, NY, 11375",
    borough: "Queens",
    description:
      "Vita Center, Inc. prides itself on providing services and classes that empower women and help them succeed in the workplace or excel in their own early childhood businesses. One of the programs we offer is Vita Teachers for Children. Through the program, women and men can gain the necessary skills and certifications to work in early childhood programs. Daycare centers, group family and family daycares require providers to have certain certifications and classes such as First Aid CPR AED and 15 Hours Health & Safety which are all classes Vita center provides.\n\nRight now Vita offer the following classes:\nPediatric First Aid/CPR/AED (provided by American Heart Association)\n15 hrs. Health and Safety\n30 hour class (required by New York State)\nCDA (120 hour) Credential\n45 hour CDA Renewal Course\nChallenging Behaviors\nFilling out the necessary books and paperwork required to open a daycare center\nGuidance in the management of programs and how to deal with inspections.\n\nWhat are the benefits of taking these classes? Vita strives to only offer programs that will have a lasting and positive impact on each individual. All of the classes Vita offers are designed to ensure that everyone can get ahead. A CDA Certification (Child Development Associate Certification) can help you in several ways in your career, including:\nAdvancing your career\nMeeting job requirements\nReinforcing your commitment to early childhood education\nProviding parents with peace of mind\nUnderstanding developmentally appropriate practice\nIncreasing your confidence\n\nVita also offers a course on Challenging Behaviors. The aim of this course is to examine the fundamental concepts and techniques in identifying challenging behaviors amongst children. Vita first examines the definition of supportive emotional and social behavior by naming specific healthy emotions, and specific social skills that promote stability in children’s behavior. Vita then analyzes the root causes of challenging behaviors in different areas of development including emotional, social, and physical development, and how these behaviors can be detrimental to a child’s success and their development in all stages of life.\n\nStudents will learn to identify these challenging behaviors through observation and by contacting and working with professionals with assessments.  Class participants then apply strategies to prevent and reduce challenging behaviors and develop healthy social emotional intelligence in children with long term and short term goals.",
    url: "http://www.vitacenterny.org/vita-teachers-for-children/",
    specialty: "General (all adults)",
    age_lower: 18,
    age_upper: null,
    email: "info@vitacenterny.org",
    contact_number: "(718) 880-7321",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.7197149,
    long: -73.8387628,
  },
  {
    name: "Vita: Workforce Development Program",
    address: "110-45 Queens Boulevard, Suite #104, Forest Hills, NY, 11375",
    borough: "Queens",
    description:
      "To get the job, you have to ace the interview. To get an interview, you have to have a great resume. Vita can offer tips and suggestions for every step of the process. A smart and qualified candidate can be passed over for someone else because of the way they interviewed, or because their resume was confusing or inconsistent. Vita is here to help you present yourself in the best and most accurate light, so that your unique skill-sets are clear to any employer who comes across your resume or LinkedIn profile. Vita offers one-on-one consultations as well as group workshops around topics such as:\nResume building\r\nExample resumes\r\nCover letters\r\nExample cover letters\r\nProfessional LinkedIn profiles\r\nInterview tips\r\nMock interviews",
    url: "http://www.vitacenterny.org/career-initiatives",
    specialty: "General (all adults)",
    age_lower: 18,
    age_upper: null,
    email: "info@vitacenterny.org",
    contact_number: "(718) 880-7321",
    requirements: null,
    org_type: "professionalServices",
    lat: 40.7197149,
    long: -73.8387628,
  },
  {
    name: "YearUp",
    address: "Wall Street Campus , 85 Broad Street, 6th Floor, New York NY 10004",
    borough: "Manhattan",
    description:
      "Year Up is a one-year, intensive training program that provides talented and motivated, yet under-served young adults, ages 18-24, with a combination of hands-on skills development, coursework eligible for college credit, corporate internships, and wraparound support.",
    url: "https://www.yearup.org/",
    specialty: "Young Adult",
    age_lower: 18,
    age_upper: 24,
    email: "yearupinfo@yearup.org",
    contact_number: null,
    requirements: null,
    org_type: "professionalServices",
    lat: 40.703984,
    long: -74.011186,
  },
];
