export default [
  {
    name: "Ali Forney Center",
    address: "224 West 35th Street, 15th Floor, New York, NY 10001",
    borough: "Manhattan",
    description:
      "The organization has grown to become the largest agency dedicated to LGBTQ homeless youths in the country—assisting nearly 1,400 youths per year through a 24-hour Drop-In Center which provides over 70,000 meals annually, medical and mental health services through an on-site clinic, and a scattered site housing program.",
    url: "www.aliforneycenter.org",
    specialty: "LGBTQ+",
    age_lower: 16,
    age_upper: 24,
    email: null,
    contact_number: null,
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Bowery Mission: Tribeca Campus",
    address: "90 Lafayette Street,New York, NY 10013",
    borough: "Manhattan",
    description:
      "Shelter program is a compassionate intervention to that cycle. Including showers, hygiene items, clean clothes, linens, and brand-new donated mattresses, the shelter program provides services in a dignified setting.\n\nGuests are also able to connect with resources to take next steps out of crisis and poverty. They also serve guests who do not necessarily need the structure of their long-term residential program, such as people who may already be working or people who do not struggle with addiction.\n\nSafe overnight shelter is offered daily. Intake occurs 7 days a week: for women from 3:00pm - 3:45pm and for men from 4:00pm - 5:00pm. Walk in or call for more information.",
    url: "https://www.bowery.org/get-help/",
    specialty: "Regular",
    email: null,
    age_lower: 18,
    age_upper: null,
    contact_number: "(212) 226-6214",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Chelsea Foyer",
    address: "202 West 24th Street, NY, NY 10011, USA",
    borough: "Manhattan",
    description:
      "The Chelsea Foyer at The Christopher provides supportive housing to young adults in their late teens and early twenties who have aged out of the child welfare system, are homeless, or at risk of homelessness. Residents participate in a personalized program of services for up to 24 months with the goal of preparing them for independent permanent housing, employment, and careers. The young men and women live semi-independently, in studio apartments or suites, while receiving a continuum of services to help them gain the competencies and confidence necessary for long-term self-sufficiency.\nCase management services are offered on-site, as are linkages to rigorous job training and placement, educational and life skills development. Foyer residents are also taught and encouraged to become completely self-sufficient, pursuing jobs with benefits to avoid the need for public assistance.",
    url: "https://goodshepherds.org/program/chelsea-foyer/",
    specialty: "Young Adults",
    email: null,
    age_lower: null,
    age_upper: null,
    contact_number: "(646) 485-3954",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Close To Home Residences- ",
    address: "480 Vermont Street, Brooklyn, NY, USA",
    borough: "Brooklyn",
    description:
      "Good Shepherd Services has two Non-Secure Placement Residences that provide long-term, residential and supportive services for teenage boys and girls who have been placed in our care by the Family Court. As part of the New York State “Close to Home” initiative, the youth are able to maintain close connections to family and other positive adults, advance their education, and work with staff to address those issues that led to placement.",
    url: "https://goodshepherds.org/program/close-to-home-residences/",
    specialty: "Youth",
    email: null,
    age_lower: null,
    age_upper: 18,
    contact_number: "(718) 788-0666,
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Coalition for the Homeless Youth",
    address: "495 Flatbush Ave, Brookyln, NY 11225",
    borough: "Brooklyn",
    description:
      "The Coalition for Homeless Youth is committed to working on behalf of runaway, homeless and street youth to ensure their rights. Youth have the right to be safe, healthy and prepared for the future. The Coalition for Homeless Youth brings together agencies and individuals from throughout New York State who share our ideals and who, by serving youth in the full context of their families, their cultures and their communities, provide a continuum of services that works towards making that ideal a reality.",
    url: "http://www.nychy.org/#home",
    specialty: "Youth Organization",
    email: "Jamie@nychy.org ",
    age_lower: 16,
    age_upper: 21,
    contact_number: "(347) 779-2352",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Covenant House NY",
    address: "550 10th Ave, New York, NY 10018",
    borough: "Manhattan",
    description:
      "Covenant House New York (CHNY) has been a leader in providing residential services to vulnerable homeless, runaway, and exploited youth.  As the largest provider of runaway and homeless youth services in New York City, CHNY serves over 1,900 young adult ages 16-24 annually with an operating budget of over 25 million dollars.  We facilitate our services using trauma-informed principles to help homeless youth leave the streets and achieve independence. We also advocate for systemic change through public policy while promoting awareness of critical issues related to youth homelessness.",
    url: "https://www.covenanthouse.org",
    specialty: "Youth Organization",
    email: "info@covenanthouse.org",
    age_lower: 14,
    age_upper: 20,
    contact_number: null,
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Family Shelters Bronx",
    address: "151 E 151st St, The Bronx, NY 10454",
    borough: "Bronx",
    description: "The Family Shelters provides shelter for parents and their children (minors)",
    specialty: "Family",
    email: null,
    age_lower: null,
    age_upper: null,
    contact_number: "(917) 521-3900",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "HRA Men's Shelter",
    address: "400 E 30th St, New York, NY 10016",
    borough: "Manhattan",
    description: "DHS Sponsored Homeless Shelter for Single Males; Open 24/7 including weekends and holidays.",
    url: "https://www1.nyc.gov/site/dhs/shelter/singleadults/single-adults-applying.page",
    specialty: "Regular ",
    email: null,
    age_lower: 18,
    age_upper: null,
    contact_number: "(718) 557-1399",
    org_type: "shelter",
    requirements:
      "The following forms of ID are very helpful during the intake process (but are not required):\n\nAny form of ID with a picture and proof of age, such as a driver's license, state-issued ID, passport or visa, welfare card or green card\nSocial Security card\nMedicaid card, if available\nIf working, your most recent pay stub",
  },
  {
    name: "Mainchance Drop In Center",
    address: "120 East 32nd Street, New York, NY 10016",
    borough: "Manhattan",
    description:
      "At Mainchance, clients can stay in emergency overnight shelter, receive a variety of services including housing, medical, social work, catch a bus to a faith-based overnight bed program and eat 3 meals a day in our kitchen. Open 24/7 365 a year",
    url: "http://www.grandcentralneighborhood.org/services/mainchance-drop-in-center/",
    specialty: "Regular ",
    age_lower: 18,
    age_upper: null,
    email: "admin@gcnssc.org",
    contact_number: "212-883-0680 Ext. 108",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Marian Hall",
    address: "337 E 17th St, New York, NY 10003",
    borough: "Manhattan",
    description:
      "Marian Hall, a community group residence, serves teenage girls who are unable to live at home. The residence is an open setting, where the young women are able to come and go to school or jobs in the community, maintain regular contact with their families and participate in social activities, while still being in a safe and structured environment where they are provided with comprehensive services to resolve the problems that led to placement and prepare them for independent adulthood. These services include individual, group and family therapy, job readiness activities, educational and vocational counseling, medical care, mentoring and recreational activities.",
    specialty: "Youth (Girls)",
    email: null,
    age_lower: null,
    age_upper: null,
    contact_number: null,
    org_type: "shelter",
    requirements: "Must have been referred by the New York City Administration for Children’s Services",
  },
  {
    name: "McLaughlin East Harlem Residence",
    address: "55 East 110th Street, NY, NY 10029, USA",
    borough: "Manhattan",
    description:
      "McLaughlin East Harlem Residence (formerly Edwin Gould Academy) is a housing program for young adults, ages 18 to 25. The East Harlem residency provides safe, affordable housing to 36 young adults in studio apartments. The residence also has 15 supportive housing units which consist of 15 one-bedroom apartments for a single parent with one child.\nIn addition to housing, McLaughlin East Harlem Residence offers a host of services and supports which include counseling, peer groups, life-skills training, and referrals-all designed to meet the emotional, employment, housing, educational, and legal needs of youth in one convenient setting.",
    url: "https://goodshepherds.org/program/edwin-gould-academy/",
    specialty: "Young Adults",
    email: null,
    age_lower: 18,
    age_upper: 25,
    contact_number: "(212) 828-2173",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Nazareth Housing",
    address: "519 East 11th Street, NY, NY 10009",
    borough: "Manhattan",
    description:
      "Through Nazareth Housing’s Housing Stability Support Project (HSSP), formerly homeless families receive extensive ongoing case management and frequent check-ins from case workers to ensure retention of housing and financial stability. Housing Counseling: Personalized plans to assist with landlord relations, rehousing, and safety; Eviction Prevention: Serves families that need assistance with rent and utlity arrears, unexpected medical costs, and other urgent family needs that threaten housing stability; Financial Coaching: Free one-on-one coaching for everything from credit repair, benefits screening, budgeting workshops, and free tax preparation; LifeLab: Year-round programming designed to build housing and economic mobility ewhile simultaneously nurturing emotional and physical wellness",
    url: "https://nazarethhousingnyc.org/prevention/",
    specialty: "Housing Prevention",
    email: "ibecker@nazarethhousingnyc.org",
    age_lower: 18,
    age_upper: null,
    contact_number: "(646) 713-2671",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "New Alternatives for LGBT Homeless",
    address: "410 W 40th St, New York New York, NY 10018",
    borough: "Manhattan",
    description:
      "New Alternatives provides a range of services designed to help LGBTQ+ youth succeed in transitioning to stable adult lives and welcomes all youth as they are with no barriers to entry. Includes support for Basic Needs, Case Management, Recreational Activities, Education, Life Skills Training, Self Expression, Testing and Prevention",
    url: "https://www.newalternativesnyc.org/",
    specialty: "LGBTQ+",
    email: "info@newalternativesnyc.org",
    age_lower: 16,
    age_upper: 30,
    contact_number: "(718) 300-0133",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "New York City Department of Homeless Services\nAdult Family Intake Center (AFIC)",
    address: "400 East 29th Street (1st Avenue)\nNew York, NY 10016 (Manhattan)",
    borough: "Manhattan",
    description: "Intake Facility for Adult Families with No Children",
    url: "https://www.hud.gov/states/new_york/homeless/familiesshelters",
    specialty: "Adults",
    email: null,
    age_lower: 18,
    age_upper: null,
    contact_number: "(212) 481-4704 or 311",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "New York City Homeless Shelter",
    address: "346 Powers Ave, The Bronx, NY 10454",
    borough: "Bronx",
    description: "Shelter for families with minor children and/or preganant women",
    url: "https://www.hud.gov/states/new_york/homeless/familiesshelters",
    specialty: "Family",
    email: null,
    age_lower: null,
    age_upper: null,
    contact_number: "(212) 361-7971",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "New York City Rescue Mission",
    address: "90 Lafayette St, New York, NY 10013",
    borough: "Manhattan",
    description: "Night shelter and meal services to homless New Yorkers of all ages",
    url: "http://nycrescue.org/",
    specialty: "Regular",
    email: null,
    age_lower: null,
    age_upper: null,
    contact_number: "(212) 226-6214",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Passaic Teen Center",
    address: "228 Hope Ave, Passaic, NJ 07055",
    borough: null,
    description: "Emergency shelter and group home for 14 runaway, homeless, and abused young men ages 11-17",
    url: null,
    specialty: null,
    email: null,
    age_lower: 11,
    age_upper: 17,
    contact_number: null,
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Patnership for the Homeless",
    address: "305 7th Ave, New York, NY 10001",
    borough: "Manhattan",
    description:
      "Homeless or Homeless-At-Risk Resource Center- \nHousing services include:\n-Offer financial assistance and landlord mediation to prevent the immediate loss of home and prevent future homelessness\n-Provide legal referrals\n-Support housing placement with vouchers, and a bank of available affordable apartments\n-Employment training and benefits screening\n-Connect to income support services offered at government offices and community partners",
    url: "https://partnershipforthehomeless.org/",
    specialty: "General (all adults)",
    email: "info@pfth.org",
    age_lower: null,
    age_upper: null,
    contact_number: "(212) 645-3444",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Project Hospitality",
    address: "100 Park Ave, Staten Island NY 10302",
    borough: "Staten Island",
    description:
      "PH seeks to realize its mission by advocating for those in need as well as providing a comprehensive continuum of care that provides the essentials of food, clothing and shelter enhanced by health and mental health services, substance abuse treatment, HIV prevention and care, domestic violence education and services, immigrant services, vocational training, transitional and permanent housing, legal and financial services and services for at-risk youth.",
    url: "https://www.projecthospitality.org/",
    specialty: "Regular",
    email: null,
    age_lower: null,
    age_upper: null,
    contact_number: null,
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Safe Horizon",
    address: "209 West 125th St. NY, NY 10002",
    borough: "Manhattan",
    description:
      "Safe Horizon is a victim assistance nonprofit that specializes in providing assistance and resources to victims of abuse and violence- including victims of child abuse, sexual abuse, human trafficking, stalking, homelessness. Specifically, they have two youth shelters located in the Lower East Side and Harlem respectively. ",
    url: "https://www.safehorizon.org/our-services/safe-place-to-stay/",
    specialty: "Youth",
    email: "SafeHorizon@safehorizon.org",
    age_lower: null,
    age_upper: 21,
    contact_number: "(212) 695-2220",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Safe Horizon",
    address: "33 Essex St. NY, NY 10027",
    borough: "Manhattan",
    description:
      "Safe Horizon is a victim assistance nonprofit that specializes in providing assistance and resources to victims of abuse and violence- including victims of child abuse, sexual abuse, human trafficking, stalking, homelessness. Specifically, they have an Overnight Shelter- to be referred to the shelter, ",
    url: "https://www.safehorizon.org/our-services/safe-place-to-stay/",
    specialty: "Youth",
    email: "LESClients@safehorizon.org",
    age_lower: null,
    age_upper: 21,
    contact_number: "(646) 602-6404",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Sylvia's Place",
    address: "446 W 36th St, New York, NY 10018",
    borough: "Manhattan",
    description:
      "Emergency shelter for LGBT+ youth that offers housing for up to 90 days, during which time housed youths are given access to STI testing, mental health services and preparation for life post housing. Offers safe free syringe walk in program as well as walk in STI testing.",
    url: "http://www.mccny.org/mccnycharities.html",
    specialty: "LGBT+",
    email: null,
    age_lower: 18,
    age_upper: 24,
    contact_number: "(212) 629-7440 ext 226",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "The Lantern Community- Jasper Hall",
    address:
      "494 8th Avenue, 20th Floor, New York, NY 10001 / Jasper Hall is located in the Bronx, address not disclosed.",
    borough: "Manhattan, shelter in the Bronx",
    description:
      "The Lantern Community seeks to create affordable housing and shelter for young families and youth graduating out of foster care. There are two specific buildings that house previously homeless youth, Jasper Hall and Savanna Hall. Jasper Hall has 53 units, 22 of which are reserved for young adults with special needs who have aged out of foster care. ",
    url: "https://lanterncommunity.org/",
    specialty: "Special needs youth",
    email: null,
    age_lower: 18,
    age_upper: 26,
    contact_number: "212.398.3073",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "The Lantern Community- Savanna Hall",
    address:
      "495 8th Avenue, 20th Floor, New York, NY 10001 / Savanna Hall is located in Washington Heights, address not disclosed.",
    borough: "Manhattan",
    description:
      "The Lantern Community seeks to create affordable housing and shelter for young families and youth graduating out of foster care. There are two specific buildings that house previously homeless youth, Jasper Hall and Savanna Hall. Savanna Hall has 72 studios, 25 of which are set aside for youth allocated for youths aging out of the foster care system.",
    url: "https://lanterncommunity.org/",
    specialty: "Youth",
    email: null,
    age_lower: 18,
    age_upper: 27,
    contact_number: "212.398.3074",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Trinity Place Shelter",
    address: "164 W 100 St, New York, NY 10025",
    borough: "Manhattan",
    description:
      "Trinity Place Shelter is a non-sectarian, 10-bed transitional shelter that provides LGBTQ+ youth and young adults with a safe place to sleep, shower, eat, and store their belongings. They provide individual and group counseling, independent living supportive services, and access to transportation.",
    url: "https://trinityplaceshelter.org/",
    specialty: "LGBT+ ",
    email: "info@trinityplaceshelter.org",
    age_lower: 18,
    age_upper: 24,
    contact_number: "(646) 580-7045",
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Urban Pathways",
    address: "575 8TH AVENUE, 16TH FLOOR , NEW YORK, NY 10018",
    borough: "Manhattan",
    description: null,
    url: "https://www.urbanpathways.org/programsandservices",
    specialty: "Regular",
    email: "outreachteam@urbanpathways.org",
    age_lower: 21,
    age_upper: null,
    contact_number: null,
    org_type: "shelter",
    requirements: null,
  },
  {
    name: "Youth Shelter Program of Westchester",
    address: "220 E 8th St, Mt Vernon, NY 10550",
    borough: "Upstate (Mount Vernon)",
    description:
      "Youth shelter with a 12-bed residential facility, on-site clinical mental health and substance abuse counseling with educational and vocational programs",
    url: "www.ysow.org/",
    specialty: "Youth Organization",
    email: "Info@ysow.org",
    age_lower: 16,
    age_upper: 21,
    contact_number: "(212) 736-7385",
    org_type: "shelter",
    requirements: null,
  },
   {
    name: "Fresh Youth Initiatives",
    address: "505 W 171st St, New York, NY 10032",
    borough: "Manhattan",
    description:
      "youth development services to low-income, first generation and immigrant youth in the washington heights area. Children participate in mental health, education, college access programs and more.",
    url: "http://freshyouth.org/",
    specialty: "Youth Organization",
    email: "info@freshyouth.org",
    age_lower: 4,
    age_upper: 18,
    contact_number: "(212) 781-1113",
    org_type: "shelter",
    requirements: null,
  },
   {
    name: "The Door",
    address: "555 Broome St, New York, NY 10013",
    borough: "Manhattan",
    description:
      "offers health, mental health, legal appointments, career & education classes, and offer referrals to nearby shelters for homeless and runaway youth ",
    url: "http://www.door.org/",
    specialty: "Youth Organization",
    email: "resources@door.org",
    age_lower: 12,
    age_upper: 24,
    contact_number: "(212) 941-9090",
    org_type: "shelter",
    requirements: null,
  },
   {
    name: "Providence House",
    address: "703 Lexington Avenue, Brooklyn, NY 11221",
    borough: "Brooklyn",
    description:
      "Providence House focuses its programs and services on two at-risk and underserved populations: women and children who are homeless and women recently paroled from prison. Providence House provides women and children in crisis with shelter, food and security as well as support services to help them transition to independence including: enrolling in education or job training programs, searching for employment, obtaining medical services and finding a permanent place to live.",
    url: "http://www.providencehouse.org/",
    specialty: "Youth and Women",
    email: "http://www.providencehouse.org/",
    age_lower: null,
    age_upper: null,
    contact_number: "(718) 455-0197",
    org_type: "shelter",
    requirements: null,
  },
     {
    name: "CMCS Sunrise Drop-In Center",
    address: "333 149th, Bronx, 10451",
    borough: "The Bronx",
    description:
      "CMCS aims to protect youth between the ages of 14-24 and, whenever  possible, to reunite them with their families through an integrated network of services. When reunification is not possible, the program aims to protect youth and help them progress towards independent living. Through daily  workshops, case management services are offered and youth are assisted in meeting their basic needs, in receiving medical and mental health services, in furthering their education, in attaining employment, and in acquiring the  skills necessary to becoming an empowered, independent individual.",
    url: "https://www.cmcs.org/our-services/at-risk-services/",
    specialty: "Youth",
    email: "FLardo-Dimarco@cmcs.org",
    age_lower: 14,
    age_upper: 24,
    contact_number: "(718) 993-5495",
    org_type: "shelter",
    requirements: null,
  },
];

